import { siteDomain } from './site-config';

export const faqs = [
  {
    q: `What is ${siteDomain}?`,
    a: `${siteDomain} is a free collection of online tools and calculators built for developers, designers, and everyday users. From generating realistic test data to calculating compound interest and exploring astrology, every tool runs instantly in your browser with no account required.`,
  },
  {
    q: 'Are all the tools completely free to use?',
    a: `Yes — every tool on ${siteDomain} is 100% free with no hidden fees, paywalls, or usage limits. Our goal is to provide high-quality utilities that are always accessible to everyone.`,
  },
  {
    q: 'Is my data private? Do you store what I enter?',
    a: 'Your privacy is a priority. All tool logic runs client-side in your browser whenever possible. We never store, log, or transmit the data you enter into our calculators or generators. What happens in your browser stays in your browser.',
  },
  {
    q: 'How do I request a new tool?',
    a: 'Have an idea for a tool we should build? Click "Request a tool" in the navigation bar and fill out the short form. We review every submission and prioritize based on community demand — popular requests make it to the roadmap fastest.',
  },
  {
    q: 'How often are new tools added?',
    a: 'We ship new tools and improvements regularly based on user requests and industry trends. Follow us or check back often — the collection keeps growing.',
  },
  {
    q: 'Can I use the generated data in production apps?',
    a: 'The data generated by our tools (fake names, emails, SSNs, phone numbers, addresses, etc.) is intentionally fictional and meant for development, testing, and demo purposes only. Never use synthetically generated personal data in live, user-facing production systems.',
  },
];
